## Server Properties
server:
  port: 8080
  compression:
    enabled: true

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pess?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    username: root    
    password: 
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.jdbc.time_zone: Asia/Colombo
  mail:
    host: smtp.gmail.com
    port: 465
    username: pessucsc@gmail.com
    password: zaq1xsw2@
    properties:
      mail.smtp.socketFactory.port : 465
      mail.smtp.socketFactory.fallback: false
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      
## Hibernate Logging
logging:
  level:
    org.hibernate.SQL: DEBUG

## App Properties
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
