package lk.ac.cmb.ucsc.pess.model;

public enum ProjectSubmissionType {
	ADD_PROJECT, ADD_SUPERVISOR, ADD_CLIENT, PROGRESS_REPORT_1, PROGRESS_REPORT_2, PROGRESS_REPORT_3, PROGRESS_REPORT_4, PROGRESS_REPORT_5, PROGRESS_REPORT_6, PROGRESS_REPORT_7, PROGRESS_REPORT_8, PROGRESS_REPORT_9, PROGRESS_REPORT_10, INTEREEM, VIVA
}
